apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: upbox
  annotations:
    meta.crossplane.io/maintainer: team-platform
    meta.crossplane.io/source: github.com/upbound/upbox
    meta.crossplane.io/description: |
      This configuration provides Upbound VMs
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: "v1.15.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: "v0.2.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: "v0.5.0"
