apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-upbox-network
spec:
  package: xpkg.upbound.io/upbound/upbound-upbox-network:v0.0.1
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-upbox
spec:
  package: xpkg.upbound.io/upbound/upbound-upbox:v0.0.1
