apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  name: upbox-aws-network
  annotations:
    render.crossplane.io/composition-path: apis/network/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
    render.crossplane.io/definition-path: apis/network/definition.yaml
spec:
  parameters:
    id: upbox-aws-network
    region: us-east-1
    vpcCidrBlock: 192.168.0.0/16
    subnets:
      - availabilityZone: us-east-1a
        type: public
        cidrBlock: 192.168.0.0/18
    deletionPolicy: Orphan
    providerConfigName: aws
