apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: aws-static-network
    uxp-guide: getting-started
  name: vpcpostgresqlinstances.staticnetwork.aws.database.example.org
spec:
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: CompositePostgreSQLInstance
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - base:
          apiVersion: rds.aws.upbound.io/v1beta1
          kind: SubnetGroup
          spec:
            forProvider:
              description: An excellent formation of subnetworks.
        name: dbsubnetgroup
        patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.subnetIds
          toFieldPath: spec.forProvider.subnetIds
          type: FromCompositeFieldPath
      - base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: SecurityGroup
          spec:
            forProvider:
              description: Allow access to PostgreSQL
              name: uxp-getting-started
        name: securitygroup
        patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.vpcId
          toFieldPath: spec.forProvider.vpcId
          type: FromCompositeFieldPath
      - base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: SecurityGroupRule
          spec:
            forProvider:
              cidrBlocks:
              - 0.0.0.0/0
              fromPort: 5432
              protocol: tcp
              securityGroupIdSelector:
                matchControllerRef: true
              toPort: 5432
              type: ingress
        name: securitygrouprule
        patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
      - base:
          apiVersion: rds.aws.upbound.io/v1beta1
          kind: Instance
          spec:
            forProvider:
              dbSubnetGroupNameSelector:
                matchControllerRef: true
              engine: postgres
              engineVersion: "12.15"
              instanceClass: db.t3.small
              passwordSecretRef:
                key: password
                namespace: upbound-system
              publiclyAccessible: false
              skipFinalSnapshot: true
              username: masteruser
              vpcSecurityGroupIdSelector:
                matchControllerRef: true
            writeConnectionSecretToRef:
              namespace: upbound-system
        connectionDetails:
        - fromFieldPath: spec.forProvider.username
          name: username
          type: FromFieldPath
        - fromConnectionSecretKey: attribute.password
          name: password
          type: FromConnectionSecretKey
        - fromFieldPath: status.atProvider.endpoint
          name: endpoint
          type: FromFieldPath
        name: rdsinstance
        patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
          - string:
              fmt: '%s-postgresql'
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.allocatedStorage
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.passwordSecretName
          toFieldPath: spec.forProvider.passwordSecretRef.name
          type: FromCompositeFieldPath
    step: patch-and-transform
  writeConnectionSecretsToNamespace: upbound-system
