apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: my-db-aws
  namespace: default
spec:
  parameters:
    storageGB: 20
    passwordSecretName: getting-started-db-pass
    class: wrongclass
  compositionSelector:
    matchLabels:
      uxp-guide: getting-started
      provider: aws
  writeConnectionSecretToRef:
    name: db-conn
