apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-vinaykumar-tawale
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # gitbash, powershell
    name: vinaykumar-tawale
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGUqtDKQsDx3xA5ApdKI0I8RmXY4CUoDIHdFJag2i6WIN6nj9HfbFenZho+W/qoe4P9eEJ3KBfyPaB1U/Xd9UR8VgZrx7TLVM21kHzd3YrL/Gz5xHrjtiyK36zv52B40NQRGLDmddI9tX+x6O3/tjqwAOpE/l5iHDd7ef0OZ6DCvDMhBmtpmgT1gwLwTjLmk0mICK2B0fp3noAKKaRwpcQaGvT+ST4UmK3A0uWEuj3Qx51yQRxx0h+5VRqZ65wVxwxjdrvAD63sCr/d+ArWcaXqY9/ThVrasfwX5qRaDU9sevXr5LE+bxDfBQyq+Mj5YxIc7uwVrQqZFpC+zD3kXo9EknUaCKlhN9l+tX0CJoAvJovezIrsUxAJ3+UJ7ljMOl14hKWeyM3THndRBYfpiMdkAlSyGeWJ92+Tvh0TZ5CazDBzsbfFcO3alOOfIPYF6JF6wbEZUKlN1AcN38l7nZwIUCrbn3j84uaX+AJMLFPHsBVtpwfxw3DH9D7LGtZ0x8= U1298348@USNYCCL40WJ7D3
