apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-len-kuykendall
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # Mac
    name: len-kuykendall
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC816f6cLe66upx+WLqIxnBlqKPex1qnmgS6/5RFX/cqqZOiQzhzc+1NCXHWdGF7J6QBbRrZI08VFd1oX+RZn6YLizjQ0OhIloi9tg565N15RaadBXz2aL+GXyqaP/KfYYN9iTWKh24wI77TFYe1IJaqpdKd0nLgiKcCufT3oIDK3kmWAx0ETw6A3k1+3GOGzUChT+sBJgIkJfKgbgCxRh/leA4Um1IN0j0O+FWThki1+jq4URA3TNpiRBrMaj6/fgxsRF7VV9L3uFBG7HYZRcbBFfOGb5O7iMoNmLj5UMIwQLQwDQpAB10vffjbq4e+1K5+4SP+wxLuicxhnRbt+9n lkuykend@USWLKCLT39KJGH5.local
