apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-dean-naqvi
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # Mac
    name: dean-naqvi
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcLcLlRZiu5MFcuMlPvV202q66DPhgdAVm7GwOJzuDozuy2UpXoe+XVTdLut+zwKQPHY6gsjHNWNtGBdlDbnFAe2zLzVujJ2pF0ySuv/8yS43aOUAy88VbJBHSELWTK1c3Q+oxUvNUs/bWvHMG5+Vge7h/NvMjuM0kNFdQm4YYkJmFL/4FxL/b3aqm5+3u17Bv0GAsbnPaHRn+5yGrrHF9uLWBK2fnrhUss6pPdpaAAa/lnQK9cnns/ulXRr1187cBE4IgIRE77SluP/Nu+7jaHy/RUlqfICFYbQDd49yIzD6AMkyYQQgx1g9QO8KOOU9uL69GpZJeyePKXlsYYpIR dean.naqvi@mmc.com
