apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-omkar-pathak
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # WSL
    name: omkar-pathak
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCupJ3MP70p5zX+OoQgHLpJSwFIJ4SKGllWQjGSZw/cRXSE7JlhDYgV4qQQzzyyrH71Nx2JSPEsDzRa0mWoApRauZ22PWETN4VJhFoULXgGMo+eLS7wYZAytYk54awou0MOiaoPZUAUKYA23p/vFsJf1UET1jzMdDUjcVz/KC97PKVF4whJ8dKrTm0wJiVylgDf9GTHmKKgrTnGc5F4nQeO9te7IkzEyU4U9rabDU1LAASP7AOWOd+ZWHlt8AmDpOGDkxYjtL2Vgatvk28uFn8kcApOIzaxTxiCbV6/OURKTEO3rFf6XUDuHkcx4b9YaMwKCFNnMb2mgd83iLrbX5BP6BAixcgu/5jbhj2SPn+qffw2bzPzJi32Rf2qX2u+hrmjkWqxz5787QmNk53r3DcOG+VaS5WcgIai1GyIhim4BXgJW74+R8+0wKhJCIe0QIJhj6b2GMx7G/aQcDBwyDr7IRhQFja6b+vquQrztIXmlnkYKSmPYh/kvj1I4QUf2oM= opathak@USMRSCLP2ND4X34
