apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-dan-howlett
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # CMD
    name: dan-howlett
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCAO0WrD9vssY1CFFt1aj57AcPd49cpDF6iPoNOXzmURGgjEyuQs0B4NvscSjRcgordZHdjc9tGWeKIIHJriIvrq3IYZMD0Ce5WY5nOr3QDFXTi8XXO596+zGOXD2RVu5N41feIWKH1Pbqc+jKBtknqeEafnz2mNFPed4TTFACEUcQcAh+ehkd5NNSOxzXWeH2x+hWqxRJQ5k5WohFd4FlC5gFdMCnroBt8aUfsHY3XMN71DhY41Yt3XKoV6Ivd3cmqeBXyJBN/lDfFjnZUbCoZVduCMf6vKhZ6yDsSvXOYmkNad86HP/YNsqXrXXoNBnwmlyMktlqAyzKtRYNXuJ2X Dan.Howlett@mmc.com
