apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-sandip-sankpal
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # WSL
    name: sandip-sankpal
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCR9G4vXjztkkL23jFMgjQUITM9jy/xEAFhvjfFQau59SHI1yjFME+Pq+jmquvteaLXqVjhjnTU+flTRBCI+DWy/eZyU/pp0OSsteE+7UvRNddaJZBE35q3obM38QShoYVXXh3ON5JvQYbO92dvj5/qf0otbKWLwmx+xufjeWm8Y1c2fWmJxFm20MLGkYv5YKhw6KBTDj7Ndzz4NwNG5kqYnkXHAWClwRaRYCENg2sD8Bbg6YoNvSz2TtCAEi72QYc0yLaf43bw71nEZjlGHoIDYpVzRE0MqV2lNPmXbpP/8KyDsMxrj9BvKfo+S9EkvZpsrJEcWn/UrfhfhwSrzYKorHVsRbj6wUuIW31J4GmWjWox9mPBTqi0cyTMx6tYahLNeYpxkmbwOPPHgS1r2aivldVRcFnzQWwkWSMa0QnvLiswkkkdyFLphARXSusliajujKB23N7tnLLy3CHi86HoZCq/kohGkTZVZlx8vLqQKP0Ms4Q2x9bK/5be13g7+v8= ssankpal@GBLDNCL30ZW5Y2
