apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-brian-moritz
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # WSL
    name: brian-moritz
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyhSyd0ThtFKipBdhamPh29TkhFBdIIEBEX5dQ4xJ34jISRY3aUgc4Nd/JImZ15/cTPqUykMxzi+cKgK87+rzo5SpFzmqVPJ+6PEbNH3XPHkBMTRv9KK4wrOegxvzUoZTJ8000j6NvPbfHyE89aUB5r68M7ZNg5mG/qbIz10H3O+F9E87Pa9kACHF+TqECKgnHhYiZQ566b6DVJypj8frDToBqAsb7BDbwYfukQahNnEAaQNxhj/W1E1KH/GYEQa0xIVfJuxKEEswmOnbi0U2onib6q93UGEu2B9JCORiXgod7xOxdciLtYvfrFCt0HHwMOHkMFV+70mF4st2b+/PgUGwqjp5qziboLehSE8QoAvbJgr/7lgqCfmkiMsLXb2SvqcMLghwI8pLb/vCZ5wOUkG64pD4z0OQpMORdpU9Mmn2U5NJJO8/3FmCnonyNtllK2OHHqnCXmjrh3i0Urtf59Qt6MgdYQou43M/ScFD1sQJBQCWBk7ji87K416cUffVVxhdzDgKusE7drfDiawvknmpcn2nYhDCvOKDfJ/wMTVLYkuAYAo+SlCDXcDmnsXkwoJfcEFCL8rAS8Vafis+tn6ag/kVKYJJ8TNCHA6tT2pbdHIb82ifGXRLf0ETwWJRU/5QW5E58YGrh2bRSE6a3lsEdRyQeFV2dny/UsPnQ/w== brian.moritz@mmc.com
