apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-oladapo-babalola
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # WSL
    name: oladapo-babalola
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRwgdO415hkUsMiSMLKCkIjbnO1C8Hobb2sSvq1fYPSN6lidmKAkt3sYZZTXBK9tltbu95BWSMBsLvAuUgr4n9SPVmzx9HAHxBySxwmrmJHLItrut2K0eqDORiBqwlNfxYk2Y43CsnQMnLsHuZCsU3ozWOzc7uPIrBbiCR9bGewQqLnFx3gZnoOgKlmyd+I0VIDZuxXf8dSq877Co3YIEjaSl+qKfq/aKw9NZX9mGLG6mfEisGupZKK5/hgTIfEkDRw0+HFqsc+Y7J6HnhkNz7JFv2ITuuc/ehwoyTxalYwEvS4aCnr59j50Bg1XsldYkpBMonFWi9kJzz1SKEQXRP mmc\u1322839@CATRNCLPH7Y4HW3
