apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-aman-pathak
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # WSL
    name: aman-pathak
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCc6IuQ5FARJjB4ayktIh05uD2+FebKhj26htcJ2Ze5E/3krCt/ZqLWUb22eWVvfEtbm+8KQY0VD54L9q89yIb8aT+n95N75FY25tCbJ6rmPQDwREYHF4N4HXIx12VI42LDVFHu5O65j8RPsh3Gzd8HRBgTyZyA3pIbNowju8iTQGW9I72lofNsphe+uwV5ODrbF6M9g8QDQj24FHvFHZDIJjw0jGEDi5wsBRCT8spjyGCl5w0vev5fmsfkoZtLrCrQSsLHjYzFKvSxDHBjvB/LYxmTPJbky2/3BecUZgzCYiaAvkImw1SIYQgbpZWxdARNqoCvmfj3It+woOHQNP264V6pw3ycIIe7VN6ZltRwehfH9AMIIUfzgpw5+D1sQi6h1rys8ecJ2O1AM83wxWKUipBzw7n1w5WFiU12Ttws9ZYtJv9nTIKi8slEiYua374OIeXZVIWV+2ADtXJJD5eaGL/LVPiryXQpygexi0YP/UayMzqYEPqV7/WSx3DJadc= aman@CATRNMLP2LKW7Y2
