apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-adam-foreman
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # Mac
    name: adam-foreman
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMWy/bxTfPGsdPDl7cOHZ+MoC9a8V01UAyh136u3cL9U+EiqhIMiE47X8gWms0/vdgifR6zOxbUSyHrPwaX8bXYWn985FMOdU4Rttubb72ovnZd0rLmVuGHpLlPsUAVtqg5vD3f6R4nuhHdaCb/M6ll1X4U18USnoUkhS3ZyhnFIOl8POhC6HZi3I58SMd9ZoYvqLVYTFjQVZ0lsURxKYv4+12VphKk0n5eXfo8VIg8EvTh10ESAAvdGj4ixJReZM1qTj6zuh4Fnso5YpfbdhKRw07z7HqyFVi06ayBQxxjXwrx8eCKJ1x94JzNFCA2F6XLZvr+9Pm3X3DLrrrgkZF/Bax8eze9j/L3MeeeiU5+oYluYAFafIKTfWhTJPlZ3CzHaw/J93GxiKEzQ7DUX6IC/rNr55ux0qdfGt0Bf5Wa/ebzT3kWstNcyfltjw8Ttgl667+ACPqtRJeK8glTm7jGpSZFYIJKVdJ7wNaeljUWIc7U8bbOzhZXu0pmAJeQQ8= aforeman@USWLKCLXL369394
