apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-babanjot
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # WSL
    name: babanjot
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChe9v8kCWtsT7JKBfC0sr/fadXeuQwRIJDF78qbEQlxG/+oJBWck1XOadG3TsH1KAUGZ73gXW4DZEiyz3qRvmWw5qrYr77dqIcsMIKKqDtbgaBrYiNrrS+zCRN0kQKnlfLUHL2s4ixvudgiwnZ08Y66Qf0vQ8dC94WbfuVTMyUN+WUkJj4gH7BA4l6qhaFOjAqKwMk5PGpFozeuHmWmodPYMBzS4gG1GJ52hbts70tx2c432LNPJfSSbI8rTxsvWQ+iaC3O5mDgJmlI2q4ncSFoNvtyEfwK7emhi7+xcedXMIIkPJflyB5DkTD20ov7p72mjNNa15dyVGeur7FlRHyQCjO+oTsEUkZMixOsT6Pqjj1e13c6isjdlFGrp26JZYt2se3eykeej0pbLD3CD3KWRZVnQq6BO8wSndmlJ3Gs/PYSjfs5PLBrg9aIffoKq5Cx6StPwcIi+Zrztzw13FDAJrjMe7xJF0DLwHpchF/njzZ1VKnMrWmEcbcW9jJU+0= babanjots@CATRNCLP4RPJ893
