apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-murtaza-usman
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # zsh (macOS)
    name: murtaza-usman
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDgYF9Q6u+siNbtCeMTz0Bid/A4dCFbyRMEeLCl+kPUYy4h/A9bX2yNsCuWVp4R6hnJ6ukKB3oXtrnuOydeNbT5AO4QBASPoY7M970gGcRq2FeusjP5a34TjTN+u7+iRxUUsO9ISo22DzTQEgQynx3z0iwDVA7r248TD6UsQ6uPOpY3S8H8lBy7mU/5UheP7ohuaicCRyjiVvM5+r/A4/5FvT8haHYp+vpSCQEyTNYsJItDjsgC/ZMNu4jgaFFsmMZiD9KwPk1SePxVT2e0rHtUF9vXJk1zrnrSc34nJn/F+if+HY+Q05Q0WhNV/3ElSe6MINazcpg7JrKuB+7qeG1pbQGvpO5jqnz37NMdhe2dIDzcTsLs/X8TXCop8UbFtg4tRu6ifv/37bHEfgSJ10Z0/sWhx77q7DmuT0CXLyWdQN3e+p2DLe1VtI4FXw3j9+vvrMdlDg6xKBYEU/JnBzF1MlkKZeZkqjIsebLdh4WIXDdsJhea82c7vB8yHbBfnmJESLw9BMnoFtIbLtiH6FEcSEILMJngpntOax4awswyZaSBONjqR62XA1ldh9vYg1nfJutGyb3F6lc5F79VJNxPtzBf7zK3UC/eJlc8D7i7g2bJbMjDMNgr1v09bMuxaJ59FqX9H++V1BG899pZ2uyPv812I8cwkdWv6KUn7RnRCw== murtaza.usman@mercer.com
