apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-pragadeeswar-padmanaban
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # WSL
    name: pragadeeswar-padmanaban
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzDqXMr/N6ROjvc4tpr5n4ZkVmX30AmwiFPgohBTV+OfP5PJJapqIVIGnAmfmkLpJKYCUKIwyzS/YLBupiFl4wsnLeattfFYL3nEjDFCuunQ6QAe6lUgJ+bNdsEP0vC+Rr2MJwUd0riCfF/XoqJbAlwR/zjbDTR2W688iyoC0E3o2kFsY09Y7XGFpQ2XOgveSFZD2s6BkI1aC84o372mzwmgjyv2NeFKiBO3E/J2Yqu40dERTpv4ooUrCLEk8HLO1A+YdThg8uZjmPbwk9LKFy3eL479AmnS8R3qMsbyjsNzDcblxq/0/gOwPbBQj7YI2Pg5pOvNydTRz6oRKx/PH65fbZ0qmkdb9CL8vmnN4sGiODnfupbi0Y58dzxy1NrR/9AW2nfkbTJ5tqn+i3aeFMzZAtTRhz8wQavQ8qTiyjLHT0jvJ5tfhN6nH1BvliGtvn5OlZxXrUEgyO+6jzi8b8l0S6Xtxk/SsmTH+4dAjXjxiyhfEtyt3zKQY5ydCmfyo04OXt/r4TZl3qwQEKFfP2LhZ/0LtqF04QWtTbcumfETMPr8oZjpNzdMCfnoZY6QRN3zqsvIz875uwhstbMEg1XriW23fLSieTVu9liiRR/IkJvIKbCxBuXrNnrRm5iygphH9LtMzYhv1N6tU0Nqq7TtFUykcd8fN9e7b3KiUA6Q== pragadeeswar@CATRNMLPGGM5HW3
