apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-arvind-subramanian
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # Mac
    name: arvind-subramanian
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4PoOuZLZJqGcwVhbO61eC3RseDUd0Qo5NjnMjOJyso9Gs8Ht1QYfLEWEfgqhnCyWDIlEKkeoqKJQ91RfEF5VCR+pMRYPDoe0PrDGHC6eE5rpPrG3LrQl2xwNJAfnwQc23DJkzLzfKITYRNerUyIANaAOuJbFTQtWZrBh1OMOt/gcqpDCnowGBPZhlpmIc3Z9E7YsHRIk/gUaFCgmHnysmMm3+PEOC+0F6p+YEP6nF/L/pLcWJetNz5sAMu1aUZVY4DGHXu7a9iOv+w92cMI/BoehFi+5mMRESTIpKhu7qpiJo/CYrM5tw1bZl07N9rkcGBT3T0UGN/dinaZKEIEL/JnMVOOQrQx4YRHrmEONRalgCjwFXdaFhdr52Iz4ys5Ui4/YrJjXCtYIhgTZslY7p+nawA1vB10CqitzoJH+p0waptLrk3YyHNJRKYDXEO9yqG/cZG8yvo7F0xvzBCb0Yyjrtb6eyQ4g3nPngmeztyBrn4vfZZt6ZGZfb4wv7ef8= u1228115@aumlbml80hmmd6t.au.mrshmc.com
