apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-mahesh-marsh-babu
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # CMD
    name: mahesh-marsh-babu
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzroDuerRopw+cpUle69nzgb+6DO6vkcI5ULTLFDWaD9c8YWnoAEK+mmw/5G6npmPrGL5rIQg5/ovNT+7QIe8Z1vR3dd7K16qXq2zC+gn6N6Mq/Dhu7mEDhQioKdncwf7Y3NtrK20LByuG03itxO/TYVMnCmjqc9GKW+6UCo0jvWGlz76AvTfqb+8Qj3+vb3pQ6moBZFXLLhE11pulei4Mr3wPtmfMDxInRpwzYdIilCIHLDDcKLuLiK1ss87sKEqNnEl5A3hfPMSon9dCER6rMZvKurRSL+UG0qUAx/vfDYAfvTzW/yF9oGa3S1T0CMeV4dayEL9W79U99gG2e7g9 us02p01\u864570@USMRSMLPDYV79Y3
