apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-jon-cheung
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # git bash
    name: jon-cheung
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD4D9E71gJ1lbhWSVJInPa+A6Ta2OOv2hs8QL5jK57k8/ILXGy11TAlp8uIv6RR32jU8/fGg2xSLC5RgdTPL/yoXU/qDjYN/nj8rfv2jO78k+/9hfLVbT0tjFD6RR0ZxMyyjxw11OUZPO2XR52YZ+ItHrSp0BCJxP23D3Ej9e/YBgkGSt3pSYW8MFaR8Q+R4uFYoiDiIadr3z49OaVWZhmN3A4PEkpKBF+BmM0geN3Hz+b0Fr6mxIgKVMU8IGVvVYW6AVLLchzSTJgIqHN3Pyp8d/P20p7Blomfm6Yux02Ot7e3jcB74FWMXhgW56tl7cAN88AUfrSmeJsMCSAPl05
