apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-sanjeevarao-dasari
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # CMD
    name: sanjeevarao-dasari
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXZziiRxSMgIAK7nIAKPFe6kpj2VA4XKz/sY3cu2l5aRk0f7KxO7Z6HvDv0T01DFOFcuvs82TuXhq0clskm5woN1F/DfCrYWusyqp/1ux2B3bZjM3SMo3JoV95wke5y6lDNWdEGCR+MKnE5kT75wdlq2U0JnOPb4T3x8CcwwYCpaaBNzV3x8MgrShehoUwWgD6r1VPPwg4Os9Ss16i13JQfLOA4xsJZeL5I+ggo+5smzbuMysaItJvwKE2jPJrI9HEIBS319JRA7xPSg03+9N0zWmB57+CVKnoGPAwQTPxlywokzG8Hx5EbgT1+X1GsMm+d+tom7k+BBkUeyVisjHz mmi_ca\u1151496@CATRNCLPFVRR893
