apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-john-taylor
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # Putty
    name: john-taylor
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCDiHWigWKWxiVQocINhRzgNMcODnRU0+3ya3v3y1hCrg78XWkAmYEoQLU8MbYzq08jBrSRgAzrC0y7zamV1zxFKhv53ZMoX6+JH/wwsGbWBA7GZhOA2miyjrRNMMv2CRsZi4DHb74Knj7YJadWxSFVprZLKT3ChHmK1wglgPKF6fbRDN+Hk6o4dLXj7682pcniVHCNQWDx2Em4DsbOu2rFaFbmEaYrH0jfe44CiR6iDYSrNIhnZmx6iCaxohOQO2eFGjAvtafquDGUurdT8WFY+SUr7D7upgUv5I87df40DIHUTssHkMHJ5GIN2pf1X++/s/IU0Pgwg0JFg4D6BMxd upbound_key
