apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-brian-lowe
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # WSL
    name: brian-lowe
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDt4Gul6z+pJjjPCdcO+5Vxrkh/RxpGQDBvSYbKxmln1y/zkEDSPxirJUOdDdI3ZL09outgHeW2JDBF9LdUb/A/7ZofltsEmNlYsiKG50zLmQUxf+jqY+Psmnxf02Paqv/oOFCPWsTDufcGLIRPOD9S0Pg2VC+cxLMmvngT2b3zUHTh/jDdHEzCXug7yRKI0pQB2FG2tXSZl8dgS1VoVwtsuaxO7MYPVkoZiQ/d/KtkbsUKJKRa/t+DhXaL0b0R2zFffTpUnfPFlb2w19qMIJqfhM0NKb5/0UqRnSv/xwh2Kd8u6I5C49jtVwANeMsSrBoIWtqBIPJRqDj6EMyagr4epnEtkKw2/PuxVCB8MPaXxUtvbmo50KA2/5XYbG9/+ioyqgwUoj8Uk0ykxmxWyLne1gPodCxFUHj5FosNfhm6kFxxgBMazPqFCcLIBpp+80ZweyGW35weI/p72DXwbg9XGSpOFkaU19lfDB0k9d4nwLcgHq3pVEabHKHRD/KRCYn4T2iZgt6ihSqpE87gsathTDyodg7wBWRgm/swxF7RTlnNTsgVS8N1IvfCj+mxRz3iZ6SVSPDQZklEwmnoXSeTGvOak/PUOYWBdZeoQUdQE4W24qYfOrmHFmGYydktHmqnfL+JVh8Oz5TNVlNiUM/V0eKHFEU2jfCUdfkcT4RBaQ== brian.lowe@mmc.com
