apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-aswinkumar-thulasiraman
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # Max
    name: aswinkumar-thulasiraman
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDyHvcbKR+LwXpWX7hqLz+MAs/m2xjdKbOf+HuL5bSm8+dZcoBV+o0V+QtcVJzcvTkENbB+sxpjQSOMhpSRAEpwcDIOvaW0FFvM0QeR7SHZOnwko3vIPY9XldAKIeE0R1r+Mgek9Ug6LDrmu0sVs0ci1OgN9og34Kf755cQNxqSaM76vhHWvUuYYSJi72f3NLlL6uvkDDuMpEISppgBO0DnNj0ZeuoiE8rDiXiiX28NNIQu5LDYJAeU5e6T/+pg1o2dNRDjotFatYac2A6MqGmvLaiMEJRzKGTxop5N294pLSin0mwNRQCG+l+95KriELSZhYLGEGhw6xCAco6Cu+f7z3WffQY+P+VvGgxmRPKtg3AGD4B3BgW0TRhOWyo9BXcVimFPfovQLqv80ISaegdJ4MZ6BOVszllzszO03bATQ/NX3ICS/t8BazzhVSELBlxZGWppBKF+PNwkhKDsBp020A6xK9UGqGI1qimpTJ1B8gpgUoAXaas+qepe3d4v7QHD0a9xed0TED1vSs7elVlyN4ANbyGu/QJUYGo/NMbW/wA4KXGd8dupwEgBJzKGVqP7tK7sFH+scwg7OylbhO/fPdKaOrj1TBI3MGCOhzjL4wNGTKj9D9K54Vimh7f0iqv/NEjYSxwtnSu2LqtSnC/4w8Sxu1VzZu5mMA1xBg5OuQ== us02p01u1104859@USDLSCLH1GAMD6T
