apiVersion: aws.platform.upbound.io/v1alpha1
kind: Upbox
metadata:
  name: upbox-mmc-kaushik-borkar
  annotations:
    render.crossplane.io/composition-path: apis/upbox/composition.yaml
    render.crossplane.io/function-path: examples/function.yaml
    render.crossplane.io/definition-path: apis/upbox/definition.yaml
spec:
  # To connect from the AWS Console to the instance, see
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-prerequisites.html
  parameters:
    # Mac
    name: kaushik-borkar
    company: mmc
    owner: team-platform
    networkId: upbox-aws-network
    size: micro
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSm+V4BnAm+YNkQCm/4vYAGhnyHV/Z3hUI6O8Jtnq7MqtH56vCt4Iuvhrh7tL6BaRsngj846rGWX6ToF3png4f5A57Jw+3GdIyY1mOZ5MUdU8cD5fiyfnUdgkreAz9ReqXp55xP6508iBg8z3RRW1ZdFZVa2znEx+pBfJR/cAZuXFHnCzAVFNCymW2qWmmZVvAsIIdFmbdHdbu1hv2TQTuCJ5/tDkMVydeTeU/WR/xbR3PWiw5YnZbtO+M6SVUv38FtBje6J4qaI/SeG6fDbrm17jU0YKB2aEo+PNwRGWLlBn9pzJ5oOE5+mwEXAtDib9WLeXh7JZF2LkMsOXsI2pFiclPyllfHWw7bTBLGNO0ufgBPlRzBhSY2ceUk7GE3+SYTtQrQ6AFCAZ9yH1wOjD18vBDEOPyiRPAk2gpzW+dHUI/CCKniTCEGmDP6q6QbTFsjmYO+HpE/DyJoKVcBdK34TTvkHBT8ruosr8oqFZpTtJJE6o7NbMZhAm/rwYqs1rQ6wHy+hKA7jTclctGSls8KgD3/T8GJ3md44VNeTmm5cCpt1j97gsfaxvvgjTJO0vxMpc176u2JPdt7v1zXCQxReYiBQ4IBVCZKRH8sHlyRCmwCnC85tlUfSItU6UnD+u9xPKS5CMbNiASZYbYoUc5X+FaE4hX1aY5OSPxvSk5KQ== kaushik.borkar@mmc.com
